<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="service1"
     targetNamespace="http://xmlns.oracle.com/20april2023/helloworld1/service1"
     xmlns:tns="http://xmlns.oracle.com/20april2023/helloworld1/service1"
     xmlns:inp1="http://www.example.org/request/input"
     xmlns:inp2="http://www.example.org/response/output"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org/request/input" schemaLocation="../Schemas/request.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org/response/output" schemaLocation="../Schemas/response.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="inpur" element="inp1:request"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="part1" element="inp2:reponse"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
