<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="service1"
     targetNamespace="http://xmlns.oracle.com/20april2023/helloworld1/service1"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/20april2023/helloworld1/service1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="BPELProcess1">
        <plnk:role name="execute_ptt" portType="tns:execute_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/20april2023/helloworld1/service1" location="service1.wsdl"/>
</wsdl:definitions>
